keys:
  - &pokon548 age1vcy4xzcz050ncalv78u94xphft9eq4cgx83pnxxqsks9w9tsd4wq7j46wc
  - &server_fwrouter age1rlxnl9ngsmfzf2k9037d42rgyd696qk3axhg5dm0u9yhk9v955zqdyt5yy
  - &server_hetzner age17lr4x65lmwzqalacmqdt3m5vmfaaywcj6yysnj8mhz3dm6euluxsm7j83f
  - &server_hetzner-core age1a5spgqkd9x0jt63xg4u9yq0zp4u58q6jsrq5gcq6d88236njdazq5c39jv # TODO: Fix this key
  - &workstation_xiaoxin age1mpn4tcwu4fnv5fn05cgzfddsf5f7mzcv0u2njefh9vaf6vptxspq3g79vp
  - &workstation_surface age100k4tfn8ks43fktwjwrrzqhe7nkc3zvn79mr0kw52h0yqdzhp4vsclvhgq

creation_rules:
  - path_regex: secrets/common.yaml$
    key_groups:
      - age:
          - *pokon548
          - *workstation_xiaoxin
          - *workstation_surface
  
  - path_regex: secrets/fwrouter.yaml$
    key_groups:
      - age:
          - *pokon548
          - *server_fwrouter

  - path_regex: secrets/hetzner.yaml$
    key_groups:
      - age:
          - *pokon548
          - *server_hetzner

  - path_regex: secrets/hetzner-core.yaml$
    key_groups:
      - age:
          - *pokon548
          - *server_hetzner-core

  - path_regex: secrets/pinepea$
    key_groups:
      - age:
          - *pokon548
          - *server_hetzner
